---------------------------------------- BUILT-IN HIGHLIGHTS ---------------------------------------
--- :help highlight-groups

local p = require 'aurorux.palette'

return {
    ColorColumn      = { link = 'CursorLine' },
    Conceal          = { fg = p.gray1.light },
    CurSearch        = { bg = p.orange.bg },
    Cursor           = {},
    lCursor          = {},
    CursorIM         = {},
    CursorColumn     = { link = 'CursorLine' },
    CursorLine       = { bg = p.gray2.dark },
    Directory        = { fg = p.blue.fg.light },
    DiffAdd          = { bg = p.green.bg },
    DiffChange       = { bg = p.yellow.bg.dark },
    DiffDelete       = { bg = p.red.bg },
    DiffText         = { bg = p.yellow.bg.light },
    EndOfBuffer      = { link = 'NonText' },
    TermCursor       = {},
    ErrorMsg         = { link = 'DiagnosticError' },
    WinSeparator     = { fg = p.gray3.dark },
    Folded           = { bold = true, italic = true, fg = p.gray2.light },
    FoldColumn       = { link = 'LineNr' },
    SignColumn       = { link = 'LineNr' },
    IncSearch        = { link = 'CurSearch' },
    Substitute       = { link = 'CurSearch' },
    LineNr           = { fg = p.gray1.light },
    LineNrAbove      = { link = 'LineNr' },
    LineNrBelow      = { link = 'LineNr' },
    CursorLineNr     = { link = 'LineNr' },
    CursorLineFold   = { link = 'FoldColumn' },
    CursorLineSign   = { link = 'SignColumn' },
    MatchParen       = { link = 'Visual' },
    ModeMsg          = { bold = true, fg = p.gray3.light },
    MsgArea          = { link = 'Normal' },
    MsgSeparator     = { link = 'WinSeparator' },
    MoreMsg          = { link = 'Question' },
    NonText          = { fg = p.gray3.dark },
    Normal           = { fg = p.normal.light, bg = p.normal.dark },
    NormalFloat      = { link = 'Normal' },
    FloatBorder      = { link = 'WinSeparator' },
    FloatTitle       = { link = 'Title' },
    FloatFooter      = { link = 'Title' },
    NormalNC         = { link = 'Normal' },
    -- Pmenu = {},
    -- PmenuSel = {},
    -- PmenuKind = {},
    -- PmenuKindSel = {},
    -- PmenuExtra = {},
    -- PmenuExtraSel = {},
    -- PmenuSbar = {},
    -- PmenuThumb = {},
    -- PmenuMatch = {},
    -- PmenuMatchSel = {},
    -- ComplMatchIns = {},
    Question         = { fg = p.blue.fg.light },
    QuickFixLine     = { bold = true, bg = p.gray2.dark },
    Search           = { link = 'Visual' },
    SnippetTabstop   = { underline = true },
    SpecialKey       = { link = 'NonText' },
    SpellBad         = { underdotted = true, sp = p.red.fg.dark },
    SpellCap         = { underdotted = true, sp = p.orange.fg.dark },
    SpellLocal       = { underdotted = true, sp = p.blue.fg.dark },
    SpellRare        = { underdotted = true, sp = p.magenta.fg.dark },
    StatusLine       = { bold = true, fg = p.gray2.light, bg = p.gray1.dark },
    StatusLineNC     = { fg = p.gray2.light, bg = p.gray1.dark },
    StatusLineTerm   = { link = 'StatusLine' },
    StatusLineTermNC = { link = 'StatusLineNC' },
    TabLine          = {},
    TabLineFill      = {},
    TabLineSel       = { bold = true, bg = p.gray3.dark },
    Title            = { bold = true, fg = p.cyan.fg.dark },
    Visual           = { bg = p.cyan.bg },
    VisualNOS        = {},
    WarningMsg       = { link = 'DiagnosticWarn' },
    Whitespace       = { link = 'NonText' },
    WildMenu         = { link = 'PmenuSel' },
    WinBar           = { bold = true, fg = p.normal.light },  -- XXX: try gray3.light
    WinBarNC         = { fg = p.gray2.light },
}
